//! Morning briefing — aggregates information from all sources into
//! a concise summary the user sees when they first open the app.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Briefing {
    /// Human-readable summary text (generated by LLM from raw data).
    pub summary: String,
    /// Structured items the briefing covers.
    pub items: Vec<BriefingItem>,
    /// When this briefing was generated.
    pub generated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BriefingItem {
    pub source: String,
    pub title: String,
    pub detail: String,
    pub priority: Priority,
    pub actionable: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Priority {
    Low,
    Normal,
    High,
    Urgent,
}

/// Build a briefing from raw source data.
pub async fn build_briefing(
    _email_summaries: &[serde_json::Value],
    _reminders: &[serde_json::Value],
    _calendar: &[serde_json::Value],
) -> Briefing {
    // TODO: Aggregate sources, call LLM to generate natural summary
    Briefing {
        summary: "No new items to report.".into(),
        items: vec![],
        generated_at: chrono::Utc::now(),
    }
}
